# Generated by scripts/release/homebrew-formula.sh in aashirvad08/x8ai-workspace.
class X8ai < Formula
  desc "Terminal-first workspace for coding with AI agents"
  homepage "https://github.com/aashirvad08/x8ai-workspace"
  url "https://github.com/aashirvad08/x8ai-workspace/releases/download/v0.2.0/x8ai-0.2.0-macos.tar.gz"
  version "0.2.0"
  sha256 "a910e9decbbb7f7a1ec23037ee2ae8c6618344cfd8d0851609dc8739c8e3a201"

  depends_on :macos

  def install
    bin.install "x8ai"
  end

  def caveats
    <<~EOS
      Run `x8ai` to open x8ai Workspace in this terminal.
    EOS
  end

  test do
    assert_equal "x8ai #{version}", shell_output("#{bin}/x8ai --version").strip
  end
end
