# Generated by scripts/release/homebrew-formula.sh in aashirvad08/x8ai-workspace.
class X8ai < Formula
  desc "Terminal-first workspace for coding with AI agents"
  homepage "https://github.com/aashirvad08/x8ai-workspace"
  url "https://github.com/aashirvad08/x8ai-workspace/releases/download/v0.3.0/x8ai-0.3.0-macos.tar.gz"
  version "0.3.0"
  sha256 "17cef75e30b2d64d6325fba1d72b0368e65cf5f0202b7c9e4c958c34b8169828"

  depends_on :macos

  def install
    bin.install "x8ai"
  end

  def caveats
    <<~EOS
      Run `x8ai` to open x8ai Workspace in this terminal.
    EOS
  end

  test do
    assert_equal "x8ai #{version}", shell_output("#{bin}/x8ai --version").strip
  end
end
